import { test, expect } from '@playwright/test';
import { mkdtempSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { randomUUID } from 'node:crypto';
import { serve } from '../src/server.ts';

let app: Awaited<ReturnType<typeof serve>>;
test.beforeAll(async () => { app = await serve(mkdtempSync(join(tmpdir(), 'aacl-ui-')), 0); });
test.afterAll(async () => { await app.close(); });

function contrastRatio(foreground: string, background: string) {
  const luminance = (cssColor: string) => {
    const channels = cssColor.match(/[\d.]+/g);
    if (!channels || channels.length < 3) throw new Error('Invalid computed color: ' + cssColor);
    const linear = channels.slice(0, 3).map(Number).map(value => value / 255).map(value => value <= 0.04045 ? value / 12.92 : ((value + 0.055) / 1.055) ** 2.4);
    return 0.2126 * linear[0]! + 0.7152 * linear[1]! + 0.0722 * linear[2]!;
  };
  const [light, dark] = [luminance(foreground), luminance(background)].sort((a, b) => b - a);
  return (light! + 0.05) / (dark! + 0.05);
}

test('C33: Chromium UI assigns existing and new Roles from Workflow editor, runs a Workflow, records and reviews Journal', async ({ page }) => {
  const errors: string[] = [];
  page.on('pageerror', e => errors.push(e.message));
  page.on('console', e => { if (e.type() === 'error') errors.push(e.text()); });
  await page.goto(`http://127.0.0.1:${app.port}`);
  await expect(page.getByRole('heading', { name: '開発方法を、育てる。' })).toBeVisible();
  await page.screenshot({ path: '/tmp/aacl-empty.png', fullPage: true });
  await page.getByRole('button', { name: '最初の資産を作成' }).click();
  const dialog = page.getByRole('dialog');
  await dialog.getByLabel('名前', { exact: true }).fill('検証手順');
  await dialog.getByLabel('説明', { exact: true }).fill('実際のデータ経路で結果を確かめる');
  await dialog.getByLabel('description（Runtime YAML）', { exact: true }).fill('実データを使う検証手順を選ぶ');
  await dialog.getByLabel('本文（Markdown）').fill('変更に関係する検証を実行し、結果を記録する。');
  await dialog.getByRole('button', { name: '保存する', exact: true }).click();
  await expect(dialog).not.toBeVisible();
  await expect(page.getByRole('heading', { name: '検証手順', exact: true })).toBeVisible();
  await expect(page.locator('.asset-grid')).toBeVisible();
  await expect(page.locator('.asset-card')).toHaveCount(1);
  await expect(page.locator('.asset-drawer')).toBeVisible();
  await expect(page.locator('.asset-layout')).toHaveCount(0);
  await expect(page.locator('.asset-main-content')).toHaveCSS('overflow', 'hidden');
  await expect(page.locator('.asset-scroll')).toHaveCSS('overflow', 'auto');
  await page.locator('.asset-drawer').getByRole('button', { name: '×', exact: true }).click();
  await expect(page.locator('.asset-drawer')).toHaveCount(0);
  await page.locator('.asset-card').click();
  await expect(page.locator('.asset-drawer')).toBeVisible();
  await expect(page.getByText('実データを使う検証手順を選ぶ', { exact: true })).toBeVisible();
  await page.getByRole('switch').click();
  await expect(page.getByRole('switch')).toHaveAttribute('aria-checked', 'true');
  await page.getByRole('button', { name: '＋ 資産を作成' }).click();
  await dialog.getByRole('button', { name: 'Role', exact: true }).click();
  await dialog.getByLabel('名前', { exact: true }).fill('検証担当');
  await dialog.getByLabel('説明', { exact: true }).fill('結果を再現して確認する');
  await dialog.getByLabel('責務・判断観点・成果責任').fill('実際の挙動と完了条件を照合する。');
  await dialog.getByRole('button', { name: '保存する', exact: true }).click();
  await expect(dialog).not.toBeVisible();
  await page.getByRole('button', { name: '紐づける', exact: true }).click();
  await dialog.getByLabel('参照する資産').selectOption({ label: 'Skill / 検証手順' });
  await dialog.getByRole('button', { name: '紐づけを保存' }).click();
  await expect(dialog).not.toBeVisible();
  await page.getByRole('button', { name: '＋ 資産を作成' }).click();
  await dialog.getByRole('button', { name: 'Model', exact: true }).click();
  await dialog.getByLabel('名前', { exact: true }).fill('実装Model');
  await dialog.getByLabel('説明', { exact: true }).fill('実装を担当するサブエージェント');
  await dialog.getByLabel('Model名', { exact: true }).fill('provider/implementer');
  await dialog.getByLabel('呼び出し方', { exact: true }).fill('Runtimeのsubagent呼び出し');
  await dialog.getByRole('button', { name: '＋ 選択肢を追加' }).click();
  await dialog.getByLabel('選択肢名').fill('実行系');
  await dialog.getByLabel('選択値').fill('codex luna');
  await dialog.getByRole('button', { name: '＋ 選択値を追加' }).click();
  await dialog.getByLabel('選択値').nth(1).fill('codex sol');
  await dialog.getByRole('button', { name: '＋ 選択肢を追加' }).click();
  await dialog.getByLabel('選択肢名').nth(1).fill('effort');
  await dialog.getByLabel('選択値').nth(2).fill('low');
  await dialog.locator('.model-choice-editor-row').nth(1).getByRole('button', { name: '＋ 選択値を追加' }).click();
  await dialog.getByLabel('選択値').nth(3).fill('high');
  await dialog.getByRole('button', { name: '保存する', exact: true }).click();
  await expect(dialog).not.toBeVisible();
  await expect(page.getByRole('heading', { name: '実装Model', exact: true })).toBeVisible();
  await page.getByRole('button', { name: '紐づける', exact: true }).click();
  await dialog.getByLabel('参照する資産').selectOption({ label: 'Skill / 検証手順' });
  await expect(dialog.getByRole('group', { name: '参照条件' })).toBeVisible();
  await dialog.getByLabel('実行系の条件').selectOption('codex sol');
  await dialog.getByLabel('effortの条件').selectOption('high');
  await dialog.getByRole('button', { name: '紐づけを保存' }).click();
  await expect(dialog).not.toBeVisible();
  await expect(page.getByText('適用条件: 実行系=codex sol AND effort=high', { exact: true })).toBeVisible();
  await page.getByRole('button', { name: '＋ 資産を作成' }).click();
  await dialog.getByRole('button', { name: 'Workflow', exact: true }).click();
  await dialog.getByLabel('名前', { exact: true }).fill('改善の確認');
  await dialog.getByLabel('説明', { exact: true }).fill('実装と確認の二工程で改善を確かめる');
  await dialog.getByRole('button', { name: '＋ 工程を追加' }).click();
  await dialog.getByLabel('工程名', { exact: true }).fill('実装');
  await dialog.getByLabel('Model').nth(0).selectOption({ label: '実装Model / provider/implementer · 実行系: codex luna / codex sol · effort: low / high（Global）' });
  await expect(dialog.locator('[name=modelChoice][data-choice-name="実行系"]')).toBeVisible();
  await dialog.locator('[name=modelChoice][data-choice-name="実行系"]').selectOption('codex sol');
  await dialog.locator('[name=modelChoice][data-choice-name="effort"]').selectOption('high');
  await expect(dialog.getByLabel('担当Role').nth(0)).toHaveAttribute('required', '');
  await dialog.getByLabel('追加指示（任意）').nth(0).fill('Roleの責務を土台にして、変更範囲を先に確認する。');
  await dialog.getByRole('button', { name: '＋ 工程を追加' }).click();
  await dialog.getByLabel('工程名', { exact: true }).nth(1).fill('確認');
  await dialog.getByLabel('Model').nth(1).selectOption({ label: '実装Model / provider/implementer · 実行系: codex luna / codex sol · effort: low / high（Global）' });
  await dialog.locator('[name=modelChoice][data-choice-name="実行系"]').nth(1).selectOption('codex luna');
  await dialog.locator('[name=modelChoice][data-choice-name="effort"]').nth(1).selectOption('low');
  await dialog.getByLabel('担当Role').nth(0).selectOption({ label: '検証担当（Global）' });
  const secondStage = dialog.locator('.stage-editor').nth(1);
  await secondStage.getByRole('button', { name: '＋ 新しいRole' }).click();
  await secondStage.getByLabel('新しいRole名').fill('レビュー担当');
  await secondStage.getByLabel('Roleの説明').fill('変更内容を独立して確認する');
  await secondStage.getByLabel('Roleの責務').fill('実際の動作と完了条件を照合する。');
  for (const [fromIndex, to, condition, label] of [[0, '確認', '実装とテストが完了した', '確認へ'], [1, '実装', '修正が必要', '戻す'], [0, '実装', '実装結果が不十分', 'やり直す'], [1, '完了', '検証結果を受け入れられる', '完了する']] as [number, string, string, string][]) {
    const stage = dialog.locator('.stage-editor').nth(fromIndex);
    await stage.getByRole('button', { name: '＋ 行き先を追加' }).click();
    const row = stage.locator('.transition-row').last();
    await row.getByLabel('行き先').selectOption({ label: to });
    await row.getByLabel('遷移条件').fill(condition);
    await row.getByLabel('表示名').fill(label);
  }
  await dialog.getByRole('button', { name: '保存する', exact: true }).click();
  await expect(dialog).not.toBeVisible();
  await page.getByRole('button', { name: '編集する', exact: true }).click();
  const editedStages = dialog.locator('.stage-editor');
  await expect(editedStages.nth(0).locator('.transition-row')).toHaveCount(2);
  await expect(editedStages.nth(1).locator('.transition-row')).toHaveCount(2);
  const firstStageEditor = editedStages.nth(0);
  const stageContent = firstStageEditor.locator('.stage-content');
  const stageTransitions = firstStageEditor.locator('.stage-transitions');
  await expect(dialog.getByRole('region', { name: '工程 1' })).toBeVisible();
  await expect(firstStageEditor.getByRole('region', { name: 'この工程からの遷移' })).toBeVisible();
  await expect(firstStageEditor.getByRole('group', { name: '遷移設定 1' })).toBeVisible();
  await expect(firstStageEditor.getByRole('group', { name: '遷移設定 2' })).toBeVisible();
  await firstStageEditor.locator('.transition-row').nth(0).getByRole('button', { name: '遷移設定 1を削除' }).click();
  await expect(firstStageEditor.getByRole('group', { name: '遷移設定 1' })).toBeVisible();
  await expect(firstStageEditor.locator('.transition-row').first().getByRole('button', { name: '遷移設定 1を削除' })).toBeVisible();
  await expect(firstStageEditor.getByRole('group', { name: '遷移設定 2' })).toHaveCount(0);
  await firstStageEditor.getByRole('button', { name: '＋ 行き先を追加' }).click();
  const restoredTransition = firstStageEditor.locator('.transition-row').last();
  await expect(firstStageEditor.getByRole('group', { name: '遷移設定 2' })).toBeVisible();
  await expect(restoredTransition.getByRole('button', { name: '遷移設定 2を削除' })).toBeVisible();
  await restoredTransition.getByLabel('遷移条件').fill('実装とテストが完了した');
  await restoredTransition.getByLabel('表示名').fill('確認へ');
  const colors = await firstStageEditor.evaluate(stage => {
    const panel = stage.querySelector<HTMLElement>('.stage-transitions')!;
    const heading = panel.querySelector<HTMLElement>('h4')!;
    const helper = panel.querySelector<HTMLElement>('p')!;
    const row = stage.querySelector<HTMLElement>('.transition-row')!;
    const legend = row.querySelector<HTMLElement>('legend')!;
    return {
      stageText: getComputedStyle(stage.querySelector<HTMLElement>('.stage-title')!).color,
      stageHelperText: getComputedStyle(stage.querySelector<HTMLElement>('.stage-content > .hint')!).color,
      stageBackground: getComputedStyle(stage).backgroundColor,
      stageBorder: getComputedStyle(stage).borderTopColor,
      panelText: getComputedStyle(heading).color,
      helperText: getComputedStyle(helper).color,
      panelBackground: getComputedStyle(panel).backgroundColor,
      panelBorder: getComputedStyle(panel).borderTopColor,
      rowText: getComputedStyle(legend).color,
      rowBackground: getComputedStyle(row).backgroundColor,
      rowBorder: getComputedStyle(row).borderTopColor
    };
  });
  expect(contrastRatio(colors.stageText, colors.stageBackground)).toBeGreaterThanOrEqual(4.5);
  expect(contrastRatio(colors.panelText, colors.panelBackground)).toBeGreaterThanOrEqual(4.5);
  expect(contrastRatio(colors.helperText, colors.panelBackground)).toBeGreaterThanOrEqual(4.5);
  expect(contrastRatio(colors.stageHelperText, colors.stageBackground)).toBeGreaterThanOrEqual(4.5);
  expect(contrastRatio(colors.rowText, colors.rowBackground)).toBeGreaterThanOrEqual(4.5);
  expect(contrastRatio(colors.stageBorder, colors.stageBackground)).toBeGreaterThanOrEqual(3);
  expect(contrastRatio(colors.panelBorder, colors.panelBackground)).toBeGreaterThanOrEqual(3);
  expect(contrastRatio(colors.panelBorder, colors.stageBackground)).toBeGreaterThanOrEqual(3);
  expect(contrastRatio(colors.rowBorder, colors.rowBackground)).toBeGreaterThanOrEqual(3);
  await expect(dialog.locator('[name=from]')).toHaveCount(0);
  const expectEditorToFit = async () => {
    const overflowing = await dialog.evaluate(root => {
      const modal = root as HTMLElement;
      const nodes = [modal, ...Array.from(modal.querySelectorAll<HTMLElement>('.stage-editor, .stage-content, .stage-transitions, .transition-row, .transition-fields'))];
      return nodes.filter(node => node.scrollWidth > node.clientWidth).map(node => node.className || node.tagName);
    });
    expect(overflowing).toEqual([]);
  };
  const standardViewport = page.viewportSize();
  expect(standardViewport?.width).toBe(1440);
  await expectEditorToFit();
  const wideContentBounds = await stageContent.boundingBox();
  const wideTransitionBounds = await stageTransitions.boundingBox();
  expect(wideContentBounds).not.toBeNull();
  expect(wideTransitionBounds).not.toBeNull();
  expect(wideTransitionBounds!.x).toBeGreaterThanOrEqual(wideContentBounds!.x + wideContentBounds!.width);
  expect(Math.abs(wideTransitionBounds!.y - wideContentBounds!.y)).toBeLessThanOrEqual(1);
  await page.setViewportSize({ width: 1050, height: standardViewport!.height });
  await expectEditorToFit();
  const atBreakpointColumns = await firstStageEditor.evaluate(stage => getComputedStyle(stage).gridTemplateColumns.split(' ').length);
  expect(atBreakpointColumns).toBe(1);
  await page.setViewportSize({ width: 1051, height: standardViewport!.height });
  await expectEditorToFit();
  const aboveBreakpointContent = await stageContent.boundingBox();
  const aboveBreakpointTransitions = await stageTransitions.boundingBox();
  expect(aboveBreakpointContent).not.toBeNull();
  expect(aboveBreakpointTransitions).not.toBeNull();
  expect(aboveBreakpointTransitions!.x).toBeGreaterThanOrEqual(aboveBreakpointContent!.x + aboveBreakpointContent!.width);
  await page.setViewportSize({ width: 880, height: standardViewport!.height });
  await expect(firstStageEditor).toBeVisible();
  await expectEditorToFit();
  const narrowContentBounds = await stageContent.boundingBox();
  const narrowTransitionBounds = await stageTransitions.boundingBox();
  expect(narrowContentBounds).not.toBeNull();
  expect(narrowTransitionBounds).not.toBeNull();
  expect(narrowTransitionBounds!.y).toBeGreaterThanOrEqual(narrowContentBounds!.y + narrowContentBounds!.height);
  const horizontalOverflow = await page.evaluate(() => document.documentElement.scrollWidth - window.innerWidth);
  expect(horizontalOverflow).toBe(0);
  await page.setViewportSize(standardViewport!);
  await page.screenshot({ path: '/tmp/aacl-workflow-editor.png', fullPage: true });
  await dialog.getByRole('button', { name: '保存する', exact: true }).click();
  await expect(dialog).not.toBeVisible();
  await expect(page.getByRole('img', { name: '改善の確認の許可遷移' })).toBeVisible();
  await expect(page.locator('path.edge')).toHaveCount(4);
  await expect(page.locator('path.edge.loop')).toHaveCount(1);
  await expect(page.getByText('検証担当 経由')).toBeVisible();
  await expect(page.getByText('実装Model（サブエージェント実行）').first()).toBeVisible();
  await expect(page.locator('.detail .editor-row').nth(1).locator('p.hint').first()).toContainText('担当Role: レビュー担当');
  await expect(page.locator('.detail .editor-row').nth(0)).toContainText('Roleの責務を土台にして、変更範囲を先に確認する。');
  await page.screenshot({ path: '/tmp/aacl-workflow.png', fullPage: true });
  await page.getByRole('button', { name: 'Runを開始', exact: true }).click();
  await dialog.getByLabel('実行する依頼').fill('動作経路を確認する');
  await dialog.getByRole('button', { name: 'Runを開始', exact: true }).click();
  await expect(dialog).not.toBeVisible();
  await expect(page.getByText('担当Role: 検証担当')).toBeVisible();
  await expect(page.getByText('Roleの責務を土台にして、変更範囲を先に確認する。', { exact: true })).toBeVisible();
  await expect(page.getByRole('button', { name: '確認へ', exact: true })).toBeVisible();
  await page.getByRole('button', { name: '確認へ', exact: true }).click();
  await dialog.getByLabel('遷移判断の報告').fill('実装内容を確認した');
  await dialog.getByRole('button', { name: '選択した遷移を実行' }).click();
  await expect(dialog).not.toBeVisible();
  await expect(page.getByRole('button', { name: '完了する', exact: true })).toBeVisible();
  await page.getByRole('button', { name: '完了する', exact: true }).click();
  await dialog.getByLabel('遷移判断の報告').fill('検証結果を報告した');
  await dialog.getByRole('button', { name: '選択した遷移を実行' }).click();
  await expect(dialog).not.toBeVisible();
  await page.getByRole('button', { name: 'Journalを記録', exact: true }).click();
  await dialog.getByLabel('Task（作業名）').fill('画面を通した実行検証');
  await dialog.getByLabel('Journal（Markdown）').fill('## 困った点\n改善候補の説明が不足した\n\n次回に保留する観測');
  await dialog.getByRole('button', { name: 'Journalを保存' }).click();
  await expect(dialog).not.toBeVisible();
  await page.getByRole('link', { name: 'Journal Review', exact: true }).click();
  await expect(page.getByText('改善候補の説明が不足した', { exact: true })).toBeVisible();
  await page.getByRole('button', { name: '＋ 改善を提案' }).click();
  await dialog.getByLabel('提案名', { exact: true }).fill('報告を具体化');
  await dialog.getByLabel('観測した状況').fill('説明が不足');
  await dialog.getByLabel('変更の内容').fill('検証手順に報告の具体化を追加');
  await dialog.getByLabel('理由', { exact: true }).fill('結果を判断しやすくする');
  await dialog.getByLabel('変更する資産').selectOption({ label: 'Skill / 検証手順' });
  await dialog.getByLabel('更新後の本文・責務').fill('検証結果と具体的な根拠を報告する。');
  await dialog.locator('[name=journalIds]').check();
  await dialog.locator('[name=insightIds]').filter({}).last().check();
  await dialog.getByRole('button', { name: '提案を保存' }).click();
  await expect(dialog).not.toBeVisible();
  await page.getByRole('button', { name: '承認', exact: true }).click();
  await dialog.getByLabel('判断の内容').fill('この変更を採用する');
  await dialog.getByRole('button', { name: '判断を記録' }).click();
  await expect(dialog).not.toBeVisible();
  await page.getByRole('button', { name: '承認した変更を適用' }).click();
  await expect(page.getByText('適用済み', { exact: true })).toBeVisible();
  await expect(page.getByText('次回に保留する観測', { exact: true })).toBeVisible();
  await page.getByRole('link', { name: '資産ライブラリ', exact: true }).click();
  await page.getByRole('searchbox').fill('検証手順');
  await page.locator('.asset-row').click();
  await expect(page.getByText('検証結果と具体的な根拠を報告する。', { exact: true })).toBeVisible();
  await page.getByText('検証担当 経由', { exact: true }).locator('xpath=ancestor::div[contains(@class, "relation")][1]').getByRole('button', { name: '参照元を編集' }).click();
  await expect(dialog.getByText('検証担当 → 参照先')).toBeVisible();
  await dialog.getByRole('button', { name: '紐づけを保存' }).click();
  await expect(dialog).not.toBeVisible();
  await page.getByRole('button', { name: '変更履歴・復元' }).click();
  await expect(dialog.getByText('現在', { exact: true }).first()).toBeVisible();
  await dialog.getByRole('button', { name: '×', exact: true }).click();
  for (const nav of ['変更履歴', '診断', '設定・接続']) {
    await page.getByRole('link', { name: nav, exact: true }).click();
    await expect(page.getByRole('heading', { name: nav, exact: true })).toBeVisible();
  }
  expect(errors).toEqual([]);
  const invalid = await page.request.post(`http://127.0.0.1:${app.port}/api/asset.save`, { data: { operationId: randomUUID(), asset: {}, provenance: { origin: 'ui' } } });
  expect(invalid.status()).toBe(400);
  await page.getByRole('link', { name: '資産ライブラリ', exact: true }).click();
  await page.getByRole('searchbox').fill('検証手順');
  await page.locator('.asset-row').click();
  await page.getByRole('button', { name: '削除する', exact: true }).click();
  await expect(dialog.getByText(/検証担当 → 検証手順/)).toBeVisible();
  await dialog.getByRole('button', { name: 'キャンセル', exact: true }).click();
  await expect(dialog).not.toBeVisible();
  await expect(page.locator('.asset-row')).toContainText('検証手順');
  await page.getByRole('button', { name: '削除する', exact: true }).click();
  await dialog.getByRole('checkbox', { name: 'このAssetの削除と一覧の参照解除を確定します' }).check();
  await dialog.getByRole('button', { name: '参照を解除して削除' }).click();
  await expect(dialog).not.toBeVisible();
  await page.getByRole('searchbox').fill('検証手順');
  await expect(page.locator('.asset-row')).toHaveCount(0);
  expect(errors).toEqual([]);
});
