import { test, expect } from '@playwright/test';
import { mkdtempSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { randomUUID } from 'node:crypto';
import { serve } from '../src/server.ts';

let app: Awaited<ReturnType<typeof serve>>;
test.beforeAll(async () => { app = await serve(mkdtempSync(join(tmpdir(), 'aacl-ui-')), 0); });
test.afterAll(async () => { await app.close(); });

test('C33: Chromium UI assigns existing and new Roles from Workflow editor, runs a Workflow, records and reviews Journal', async ({ page }) => {
  const errors: string[] = [];
  page.on('pageerror', e => errors.push(e.message));
  page.on('console', e => { if (e.type() === 'error') errors.push(e.text()); });
  await page.goto(`http://127.0.0.1:${app.port}`);
  await expect(page.getByRole('heading', { name: '開発方法を、育てる。' })).toBeVisible();
  await page.screenshot({ path: '/tmp/aacl-empty.png', fullPage: true });
  await page.getByRole('button', { name: '最初の資産を作成' }).click();
  const dialog = page.getByRole('dialog');
  await dialog.getByLabel('名前', { exact: true }).fill('検証手順');
  await dialog.getByLabel('説明', { exact: true }).fill('実際のデータ経路で結果を確かめる');
  await dialog.getByLabel('本文（Markdown）').fill('変更に関係する検証を実行し、結果を記録する。');
  await dialog.getByRole('button', { name: '保存する', exact: true }).click();
  await expect(dialog).not.toBeVisible();
  await expect(page.getByRole('heading', { name: '検証手順', exact: true })).toBeVisible();
  await page.getByRole('switch').click();
  await expect(page.getByRole('switch')).toHaveAttribute('aria-checked', 'true');
  await page.getByRole('button', { name: '＋ 資産を作成' }).click();
  await dialog.getByRole('button', { name: 'Role', exact: true }).click();
  await dialog.getByLabel('名前', { exact: true }).fill('検証担当');
  await dialog.getByLabel('説明', { exact: true }).fill('結果を再現して確認する');
  await dialog.getByLabel('責務・判断観点・成果責任').fill('実際の挙動と完了条件を照合する。');
  await dialog.getByRole('button', { name: '保存する', exact: true }).click();
  await expect(dialog).not.toBeVisible();
  await page.getByRole('button', { name: '紐づける', exact: true }).click();
  await dialog.getByLabel('参照する資産').selectOption({ label: 'Skill / 検証手順' });
  await dialog.getByRole('button', { name: '紐づけを保存' }).click();
  await expect(dialog).not.toBeVisible();
  await page.getByRole('button', { name: '＋ 資産を作成' }).click();
  await dialog.getByRole('button', { name: 'Workflow', exact: true }).click();
  await dialog.getByLabel('名前', { exact: true }).fill('改善の確認');
  await dialog.getByLabel('説明', { exact: true }).fill('実装と確認の二工程で改善を確かめる');
  await dialog.getByRole('button', { name: '＋ 工程を追加' }).click();
  await dialog.getByLabel('工程名', { exact: true }).fill('実装');
  await dialog.getByLabel('完了条件', { exact: true }).fill('実装内容を確認できる');
  await dialog.getByRole('button', { name: '＋ 工程を追加' }).click();
  await dialog.getByLabel('工程名', { exact: true }).nth(1).fill('確認');
  await dialog.getByLabel('完了条件', { exact: true }).nth(1).fill('検証結果を報告した');
  await dialog.getByLabel('担当Role').nth(0).selectOption({ label: '検証担当（Global）' });
  const secondStage = dialog.locator('.stage-editor').nth(1);
  await secondStage.getByRole('button', { name: '＋ 新しいRole' }).click();
  await secondStage.getByLabel('新しいRole名').fill('レビュー担当');
  await secondStage.getByLabel('Roleの説明').fill('変更内容を独立して確認する');
  await secondStage.getByLabel('Roleの責務').fill('実際の動作と完了条件を照合する。');
  for (const [from, to, type, label] of [['実装', '確認', 'next', '確認へ'], ['確認', '実装', 'return', '戻す'], ['実装', '実装', 'retry', 'やり直す'], ['確認', '完了', 'complete', '完了する']]) {
    await dialog.getByRole('button', { name: '＋ 遷移を追加' }).click();
    const row = dialog.locator('.transition-row').last();
    await row.getByLabel('遷移元').selectOption({ label: from });
    await row.getByLabel('遷移先').selectOption({ label: to });
    await row.getByLabel('種別').selectOption(type);
    await row.getByLabel('表示名').fill(label);
  }
  await dialog.getByRole('button', { name: '保存する', exact: true }).click();
  await expect(dialog).not.toBeVisible();
  await expect(page.getByRole('img', { name: '改善の確認の許可遷移' })).toBeVisible();
  await expect(page.locator('path.edge')).toHaveCount(4);
  await expect(page.locator('path.edge.retry')).toHaveCount(1);
  await expect(page.getByText('検証担当 経由')).toBeVisible();
  await expect(page.locator('.detail').getByText('レビュー担当', { exact: true })).toBeVisible();
  await page.screenshot({ path: '/tmp/aacl-workflow.png', fullPage: true });
  await page.getByRole('button', { name: 'Runを開始', exact: true }).click();
  await dialog.getByLabel('実行する依頼').fill('動作経路を確認する');
  await dialog.getByRole('button', { name: 'Runを開始', exact: true }).click();
  await expect(dialog).not.toBeVisible();
  await expect(page.getByRole('button', { name: '確認へ', exact: true })).toBeVisible();
  await page.getByRole('button', { name: '確認へ', exact: true }).click();
  await dialog.getByLabel('完了報告').fill('実装内容を確認した');
  await dialog.getByRole('button', { name: '選択した遷移を実行' }).click();
  await expect(dialog).not.toBeVisible();
  await expect(page.getByRole('button', { name: '完了する', exact: true })).toBeVisible();
  await page.getByRole('button', { name: '完了する', exact: true }).click();
  await dialog.getByLabel('完了報告').fill('検証結果を報告した');
  await dialog.getByRole('button', { name: '選択した遷移を実行' }).click();
  await expect(dialog).not.toBeVisible();
  await page.getByRole('button', { name: 'Journalを記録', exact: true }).click();
  await dialog.getByLabel('Task（作業名）').fill('画面を通した実行検証');
  await dialog.getByLabel('Journal（Markdown）').fill('## 困った点\n改善候補の説明が不足した\n\n次回に保留する観測');
  await dialog.getByRole('button', { name: 'Journalを保存' }).click();
  await expect(dialog).not.toBeVisible();
  await page.getByRole('link', { name: 'Journal Review', exact: true }).click();
  await expect(page.getByText('改善候補の説明が不足した', { exact: true })).toBeVisible();
  await page.getByRole('button', { name: '＋ 改善を提案' }).click();
  await dialog.getByLabel('提案名', { exact: true }).fill('報告を具体化');
  await dialog.getByLabel('観測した状況').fill('説明が不足');
  await dialog.getByLabel('変更の内容').fill('検証手順に報告の具体化を追加');
  await dialog.getByLabel('理由', { exact: true }).fill('結果を判断しやすくする');
  await dialog.getByLabel('変更する資産').selectOption({ label: 'Skill / 検証手順' });
  await dialog.getByLabel('更新後の本文・責務').fill('検証結果と具体的な根拠を報告する。');
  await dialog.locator('[name=journalIds]').check();
  await dialog.locator('[name=insightIds]').filter({}).last().check();
  await dialog.getByRole('button', { name: '提案を保存' }).click();
  await expect(dialog).not.toBeVisible();
  await page.getByRole('button', { name: '承認', exact: true }).click();
  await dialog.getByLabel('判断の内容').fill('この変更を採用する');
  await dialog.getByRole('button', { name: '判断を記録' }).click();
  await expect(dialog).not.toBeVisible();
  await page.getByRole('button', { name: '承認した変更を適用' }).click();
  await expect(page.getByText('適用済み', { exact: true })).toBeVisible();
  await expect(page.getByText('次回に保留する観測', { exact: true })).toBeVisible();
  await page.getByRole('link', { name: '資産ライブラリ', exact: true }).click();
  await page.getByRole('searchbox').fill('検証手順');
  await page.locator('.asset-row').click();
  await expect(page.getByText('検証結果と具体的な根拠を報告する。', { exact: true })).toBeVisible();
  await page.getByRole('button', { name: '参照元を編集' }).click();
  await expect(dialog.getByText('検証担当 → 参照先')).toBeVisible();
  await dialog.getByRole('button', { name: '紐づけを保存' }).click();
  await expect(dialog).not.toBeVisible();
  await page.getByRole('button', { name: '変更履歴・復元' }).click();
  await expect(dialog.getByText('現在', { exact: true }).first()).toBeVisible();
  await dialog.getByRole('button', { name: '×', exact: true }).click();
  for (const nav of ['変更履歴', '診断', '設定・接続']) {
    await page.getByRole('link', { name: nav, exact: true }).click();
    await expect(page.getByRole('heading', { name: nav, exact: true })).toBeVisible();
  }
  expect(errors).toEqual([]);
  const invalid = await page.request.post(`http://127.0.0.1:${app.port}/api/asset.save`, { data: { operationId: randomUUID(), asset: {}, provenance: { origin: 'ui' } } });
  expect(invalid.status()).toBe(400);
});
